# Generated by Django 2.2.7 on 2019-11-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAdress', models.CharField(max_length=15, verbose_name='IP Adresi')),
                ('username', models.CharField(max_length=30, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
