# Generated by Django 2.2.6 on 2019-10-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pidata',
            name='timestamp',
        ),
    ]
