# Generated by Django 2.2.6 on 2019-10-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_remove_pidata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidata',
            name='zaman',
            field=models.CharField(default='', max_length=50, verbose_name='Tarih'),
        ),
    ]
